### ISSUE TITLE
Automatically grab the Git tag to create the package version in our publish GitHub Action

### ISSUE THREAD

**Issue by thewtex** [KitwareMedical/tensorboard-plugin-3d#27]
With a tool like versioneer or something similar

**Comment by bnmajor** [comment]
It seems that Versioneer is no longer maintained so I decided to go with [setuptools-scm](https://pypi.org/project/setuptools-scm/) which seems to be highly recommended and is successfully being used currently with our [HEXRD](https://github.com/HEXRD/hexrd)/[HEXRDGUI](https://github.com/HEXRD/hexrdgui) project.

**Comment by thewtex** [comment]
Did not work releases 1.1.2: https://github.com/KitwareMedical/tensorboard-plugin-3d/runs/4960190756?check_suite_focus=true
