### ISSUE TITLE
Toggle Label and Image is toggling both

### ISSUE THREAD

**Issue by GiudiceVitor** [KitwareMedical/tensorboard-plugin-3d#65]
When you press on the "eye" indicator to toggle on/off the label and the imagem, it is toggling both, not just the one you press.
I expected that when I press to toggle the label, the imagem would continue to show, but instead it also disapears.

**Comment by bnmajor** [comment]
Indeed, this is the behavior at this moment. Separating the label from the image in order to toggle on/off one at a time is a little tricky and is not something we currently support unfortunately. For now images and labels must be loaded separately if you wish to view them separately.

**Comment by GiudiceVitor** [comment]
Understood. Is there a way to plot 2 images in the same page to view them side by side, instead of of different pages?

**Comment by bnmajor** [comment]
Not at the moment, although we could add support for checkerboarding, which overlays two images on top of one another (with the option to adjust the blend between the two). I will open an issue for this but I am not sure how soon I will be able to get the updates in.

I am not sure if you need to use TensorBoard specifically but if you are just in need of visualization tools in your notebook you may want to consider [itkwidgets](https://itkwidgets.readthedocs.io/en/latest/quick_start_guide.html) in the meantime. This uses the same visualization backend but the pre-release channel has a lot of newer features that this plugin does not yet include, including blending images (you can download and try out the [ThinPlateSpline example](https://github.com/InsightSoftwareConsortium/itkwidgets/blob/main/examples/integrations/itk/ThinPlateSpline.ipynb) to see how this works).

**Comment by GiudiceVitor** [comment]
Great! Thanks for the insights :)
